ASP.NetCore.WordShuffle/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ASP.NetCore.WordShuffle.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ASP.NetCore.WordShuffle/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NetCore.WordShuffle.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;   
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        public string ShuffleWord { get; set; }
        public string Name { get; set; }
        public string Word { get; set; }
        public void OnGet()
        {
            ShuffleWord = "enter the word you want to shuffle";
        }
        
        public void OnPostSubmit(ShuffleWordModel Property)
        {
            ShuffleWord = "successfully shuffled";
            SuffleMember(Property.Word, Property.Name);
        }

        public void SuffleMember(string word, string name)
        {
            char[] array = word.ToCharArray();
            Random rng = new Random();
            int n = array.Length;
            while (n > 1)
            {
                n--;
                int k = rng.Next(n + 1);
                var value = array[k];
                array[k] = array[n];
                array[n] = value;
            }
            Word = new string(array);
            Name = name;
        }
        
    }
    public class ShuffleWordModel
    {
        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Word { get; set; }
    }
}

ASP.NetCore.WordShuffle/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NetCore.WordShuffle.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;
        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ASP.NetCore.WordShuffle/Pages/User.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NetCore.WordShuffle.Pages
{
    public class UserModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public UserModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ASP.NetCore.WordShuffle/Pages/Index.cshtml
@page
@model IndexModel;
@{
    ViewData["Title"] = "Home page";
    ViewData["Indexname"] = "SampleName";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <div>
        <form method="post" >
            <fieldset>
                <legend>ADD SAMPLE WORD</legend>
                <div>
                    <label for="Word">Word:</label>
                    <input type="text" name="Word" value="" />
                </div>
                <div>
                    <label for="Name">Name:</label>
                    <input type="text" name="Name" value="" />
                </div>
                <div>
                    <label>&nbsp;</label>
                    <input type="submit" value="Submit" class="submit" asp-page-handler="Submit"/>
                </div>
            </fieldset>
            <p>@Model.Word from @Model.Name</p>
        </form>
        <h3>@Model.ShuffleWord</h3>
    </div>
</div>



ASP.NetCore.WordShuffle/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NetCore.WordShuffle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NetCore.WordShuffle.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ASP.NetCore.WordShuffle</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/User">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP.NetCore.WordShuffle - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NetCore.WordShuffle/Pages/User.cshtml
@page
@model UserModel
@{
    ViewData["Title"] = "User List";
    ViewData["User"] = "Sample User";
}
<h1>@ViewData["Title"]</h1>

<p>This is a uers page</p>

<div>
    <p>@ViewData["User"]</p>
</div>